### ISSUE TITLE
skull duplication

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeCommon#2259]
**I am currently running**

- SpongeForge version: 1.12.2-2825-7.1.6-RC3705

- Plugins/Mods:
Prism, GriefPrevention

**Issue Description**

https://github.com/prism/Prism/issues/132#issuecomment-491498302

**Comment by CaptainSisko** [comment]
Just tested this with the following

Mods: none
Forge: 1.12.2-14.23.5.2825
Sponge: 1.12.2-2825-7.1.6-RC3711
Plugins: Nucleus-1.9.3-S7.1-MC1.12.2-plugin

This issue requires a sponge plugin to be added before it occurs.

Simply placing a skull on the ground and breaking it will give you 2 skulls in return.

**Comment by LXGaming** [comment]
Sponge is capturing the entity spawn twice, I put a log message in `PhaseContext::captureEntity` and found that the method got called twice: https://gist.github.com/LXGaming/2b918d80b5c2e03ce080a2010d75f743 (Line 13 & 45)

This recently added Mixin is triggering the 2nd capture:
https://github.com/SpongePowered/SpongeCommon/blob/5f19dd24c9969574b90d36caa1552015a383d94a/src/main/java/org/spongepowered/common/mixin/core/server/management/MixinPlayerInteractionManager.java#L547-L581

**Comment by JBYoshi** [comment]
I can't reproduce this on SpongeForge 3716 (using `-Dsponge.shouldFireAll=true`). I think it was fixed by 98f2f9ae2ea1febffd6dfe043a044145721b14ba.

**Comment by phit** [comment]
this still happens without shouldFireAll, according to someone on Discord

**Comment by runescapejon** [comment]
It seem it's you can reproduce this just by going into survival not creative using `3716 `.

**Comment by JBYoshi** [comment]
Finally able to reproduce this. The problem causing this appears to be that `BlockSkull` expects the block and tile entity to be removed when `harvestBlock()` is called. However, Sponge re-adds the tile entity during `harvestBlock()` to fix https://github.com/SpongePowered/SpongeForge/issues/2709.

**Comment by JBYoshi** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/6b2d3b3e9eeec202ac1bccc5e79cd628644d58ca.
