### ISSUE TITLE
Title packets are cached when they shouldn't be

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeCommon#336]
When sending a [`Title`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/text/title/Title.java) to `Player`s, the `subtitle` and `title` packets [are cached](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/api/text/title/MixinTitle.java#L54) along with the others, causing wrong `Text`s being sent to players (translations).

**Comment by Zidane** [comment]
@kashike 

Agreed. If the caching is necessary, it should be a map of Locale, Packet[]....

**Comment by Minecrell** [comment]
I think that broke together with [the locale changes](https://github.com/SpongePowered/SpongeForge/commit/032f57ac9adb3fc7826cca7ab9190a470268fe4b) @zml2008 made, I'll fix this in the next few days.

**Comment by Minecrell** [comment]
Fixed in #364

**Comment by kashike** [comment]
Not fixed.
https://github.com/SpongePowered/SpongeCommon/issues/421
