### ISSUE TITLE
SlotAdapter.offer() and SlotAdapter.set() do not set a result type before returning

### ISSUE THREAD

**Issue by catageek** [SpongePowered/SpongeCommon#441]
offer() and set() omit to call result.type() before calling result.build() and return.

This triggers an IllegalStateException because the type is null.

**Comment by Mumfrey** [comment]
This was fixed [two weeks ago](https://github.com/SpongePowered/SpongeCommon/commit/27705f6ff539bf00288ccbd3995ec2adfbe90b48). Ensure you're running the latest build.

**Comment by catageek** [comment]
Unfortunately SlotAdapter was not fixed. Here is the exception with the latest build:

java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:161) ~[minecraft_server.1.8.9.jar:?]
        at org.spongepowered.api.item.inventory.transaction.InventoryTransactionResult$Builder.build(InventoryTransactionResult.java:182) ~[InventoryTransactionResult$Builder.class:1.8.9-3.1.0-BETA-190]
        at org.spongepowered.common.item.inventory.adapter.impl.slots.SlotAdapter.offer(SlotAdapter.java:176) ~[SlotAdapter.class:1.8.9-3.1.0-BETA-190]

Also, SlotAdapter.isEmpty() returns always true. This should be fixed too.

**Comment by Mumfrey** [comment]
Ah ok, thanks for reporting. I'll roll up a fix.
