### ISSUE TITLE
DestructEntityEvent missing Cause for Items in Fire/Lava

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/SpongeCommon#717]
When throwing an Item into Fire or Lava the item is destroyed and the Cause is only the item itself.
`Cause[{Name=Source, Object={EntityItem['item.tile.stone.stone'/921, l='world', x=122,65, y=63,00, z=35,43]}}]`

I would excpect having either some kind of DamageSource or the Block that caused the Item to be destroyed.

**Comment by bloodmc** [comment]
@Faithcaio is this fixed with latest build?

**Comment by Faithcaio** [comment]
It now contains the player "owning" the item but still not the Fire or Lava that destroyed the item.

`EntityItem['item.tile.stone.stone'/1086, l='world', x=135,23, y=63,45, z=31,77]
EntityPlayerMP['Faithcaio'/1071, l='world', x=134,51, y=63,00, z=31,94]`

**Comment by Faithcaio** [comment]
Is it possible to have BlockDamageSource? With your solution you cannot differentiate between lava and fire (both are labeled as inFire).

**Comment by gabizou** [comment]
> Entity#moveEntity:797 this.dealFireDamage(1);

This is already mixed in appropriately [here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java#L273-L296)



> Entity#onEntityUpdate:387 this.attackEntityFrom(DamageSource.onFire, 1.0F);

This isn't when you're *in* fire, this is when you're *on* fire, in which case there is no `BlockDamageSource`

**Comment by Faithcaio** [comment]
My problem was that the DamageSource in DesctructEntityEvent often is the one where the item is "on fire". As it is the last damage that was applied to it.

bloodmc suggested in IRC to check for the block using the entity location to determine whether an item got destroyed by being thrown into fire or into lava, that works fine but it would be much more convenient if the Block causing the fire is always inlcuded in the cause.
